### ISSUE TITLE
Error HH8: There's one or more errors in your config file:

### ISSUE THREAD

**Issue by amrosaeed** [PureStake/moonbeam-uniswap#1]
* Invalid value {"url":"https://rpc.testnet.moonbeam.network","accounts":[null],"chainId":1287} for HardhatConfig.networks.moonbase - Expected a value of type HttpNetworkConfig.
  
To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

**Comment by amrosaeed** [comment]
i spin a stand alone node and try but it didnt work

**Comment by albertov19** [comment]
You need to provide the Private Key for the deployment script. You can see your `accounts: [null]` which is not valid
