### ISSUE TITLE
Swap button doesnt automatically get available after approve

### ISSUE THREAD

**Issue by Berthje** [PureStake/moonbeam-uniswap#3]
After you approve token it doesnt automatically make the swap button 'blue' or 'avalailable'. You need to manually refresh the page first to click swap, which is not how it should be. please fix ASAP.

**Comment by albertov19** [comment]
![image](https://user-images.githubusercontent.com/64150856/142048253-8c8e77c3-252b-4e2e-893b-1b01a482ed22.png)

In the demo website, the swap button works after the approve tx goes through. Either way this repo is "forked" from Uniswap V2 interface, so the issue should be open there.

However, I don't think there is an issue as the image suggests.
